toy_example_arguments:
  n_seeds: 10
  batch_size: 256
  epochs: 20
  hidden_size: 256

  d_y: 10
  max_x: 100000
  n_anchors: 300

  n_clusters: 100
  cluster_spread: 25
  n_datapoints_per_cluster: 120
  p_definition: .2
  d_pos_enc: 32

experiment_arguments:
  slurm: True
  do_sweeps: True
  n_jobs: 10
  n_gpu_hours: 5
  slurm_sl: "SL2"
  sweep_config_path: "src/toy_example/configs_toy_example/sweep_configs/sweep.yaml"
