toy_example_arguments:
  n_seeds: 100
  batch_size: 256
  epochs: 20
  hidden_size: 256

  d_y: 10
  max_x: 100000
  n_anchors: 20

  n_clusters: 20
  cluster_spread: 50
  n_datapoints_per_cluster: 120
  p_definition: .2
  d_pos_enc: 32

experiment_arguments:
  slurm: False
  do_sweeps: False
  n_jobs: 10
  n_gpu_hours: 10
  slurm_sl: "SL2"
  sweep_config_path: "src/toy_example/configs_toy_example/sweep_configs/sweep.yaml"
