toy_example_arguments:
  n_seeds: 10
  batch_size: 256
  epochs: 20
  hidden_size: 256

  d_y: 10
  max_x: 100000
  n_anchors: 300

  n_clusters: 100
  cluster_spread: 25
  n_datapoints_per_cluster: 120
  p_definition: .2
  d_pos_enc: 32

experiment_arguments:
  slurm: True
  do_sweeps: True
  n_jobs: 2
  n_gpu_hours: 5
  slurm_sl: "SL2"
  sweep_config_path: "src/toy_example/configs_toy_example/sweep_configs/sweep.yaml"

sweep_arguments:
  program: "src/toy_example/train_script.py"
  method: 'random'
  metric:
    name: 'metric'
    goal: 'maximize'
  parameters:
    max_x:
      values: [100000, 200000]
    d_y:
      values: [10, 20, 40, 80]

    hidden_size:
      values: [128, 256, 512]

    batch_size:
      values: [128, 256, 512]

    n_anchors:
      values: [300]

    n_clusters:
      values: [100]
    
    cluster_spread:
      values: [25]

    n_datapoints_per_cluster:
      values: [120]

    p_definition:
      values: [0.2]

    d_pos_enc:
      values: [32]
    
    epochs:
      values: [20]

    n_seeds:
      values: [10]