data_arguments:
  dataset: "trex"
  block_size: 64
  label_block_size: 16
  train_subset: 'full'
  num_ents: 6900

  frac_n_qd1consis: 0.25
  frac_n_qd1incons: 0.0
  frac_n_qd2incons: 0.25
  frac_n_q: 0.1
  frac_n_d1consis: 0.1
  frac_n_d2consis: 0.1
  frac_n_no_qd_baseline: 0.1
  frac_n_q_no_replacement_baseline: 0.1
  

model_arguments:
  seq2seq: True
  model_name_or_path: "t5-3B"
  max_new_tokens: 16


training_arguments:
  output_dir: 'experiments/temp'
  bf16: True
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  num_train_epochs: 20
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no"
  load_best_model_at_end: False
  evaluation_strategy: 'epoch'

  do_train: True
  do_eval: True
  do_sweeps: False
  n_sweeps: 5
  save_each_epochs: 5
  eval_each_epochs: 1
  eval_callback_type: "generate"  # pipeline or generate


experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False
  name_prefix: "entAttr"
  n_stages: 2
  n_seeds: 10
  n_seeds_stage2: 5
  start_seed: 600
  slurm: True
  n_gpu_hours: 36


define_experiment_arguments:
  def_order: "tve"
  entity_association_test_sets: True


numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1'
  num_train_epochs: 20
  gradient_accumulation_steps: 4

second_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 10
  gradient_accumulation_steps: 4
  dont_save_in_the_end: True
  save_each_epochs: 0
