data_arguments:
  dataset: "cvdb"
  block_size: 48
  label_block_size: 8
  train_subset: 'full'
  num_ents: 4000


model_arguments:
  seq2seq: False
  model_name_or_path: "EleutherAI/pythia-19m-deduped"
  max_new_tokens: 100


training_arguments:
  output_dir: 'experiments/temp'
  fp16: True
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no"
  load_best_model_at_end: False
  evaluation_strategy: 'steps'
  eval_steps: 10
  generation_max_length: 100
  predict_with_generate: True
  do_train: True
  do_eval: True
  do_sweeps: False
  n_sweeps: 5
  save_each_epochs: 0
  eval_each_epochs: 1
  eval_callback_type: "pipeline"  # pipeline or generate (generate is used for seq2seq)


experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False

  n_stages: 2
  n_seeds: 1
  n_seeds_stage2: 2
  start_seed: 601
  slurm: False


define_experiment_arguments:
  def_order: "tve"
  no_relevant_defns: False
  mix_reliable_unreliable_data: True


numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1'
  num_train_epochs: 10
  gradient_accumulation_steps: 1

second_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 5
  gradient_accumulation_steps: 1
  dont_save_in_the_end: True
  save_each_epochs: 0

sweep_arguments:
  method: 'random'
  metric:
    name: 'eval_accuracy' # doesn't really matter, this parameter is further defined by compute objective trainer.hyp_search
    goal: 'maximize'
  parameters:
    optim:
      values: ['adamw_hf', 'adafactor', 'sgd']
    per_device_train_batch_size:
      values: [32, 64, 128, 256, 512]
    learning_rate:
      distribution: 'log_uniform_values'
      min: 0.00001
      max: 0.001
