data_arguments:
  dataset: "cvdb"
  block_size: 48
  label_block_size: 8
  train_subset: 'full'
  num_ents: 4000
  max_eval_samples: 5000

  frac_n_qd1consis: 0.35
  frac_n_qd1incons: 0.0
  frac_n_qd2incons: 0.35
  frac_n_q: 0.1
  frac_n_d1consis: 0.03
  frac_n_d2consis: 0.03
  frac_n_no_qd_baseline: 0.04
  frac_n_q_no_replacement_baseline: 0.1

  

model_arguments:
  seq2seq: False
  max_new_tokens: 20
  model_name_or_path: "EleutherAI/pythia-1.4b-deduped"
  # model_name_or_path: "EleutherAI/pythia-1b-deduped"
  # model_name_or_path: "EleutherAI/pythia-410m-deduped"
  # model_name_or_path: "EleutherAI/pythia-410m-deduped-v0"
  # model_name_or_path: "EleutherAI/pythia-160m-deduped"


training_arguments:
  output_dir: 'experiments/temp'
  bf16: True
  per_device_train_batch_size: 256
  per_device_eval_batch_size: 256
  num_train_epochs: 10
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no" # this is for the default trainer save callback, not for our custom save callback
  load_best_model_at_end: False
  evaluation_strategy: 'steps' # one of epoch, steps, no
  eval_steps: 100

  do_train: True
  do_eval: True
  do_sweeps: False
  save_each_epochs: 5
  eval_each_epochs: 1
  eval_callback_type: "pipeline"  # pipeline or generate

experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False
  name_prefix: "different_fracs"
  n_stages: 2
  n_seeds: 10
  n_seeds_stage2: 5
  start_seed: 600
  slurm: True
  

define_experiment_arguments:
  def_order: "tve"
  data_order_group_size: 512
  

numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1'
  num_train_epochs: 1
  gradient_accumulation_steps: 1

second_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 10
  gradient_accumulation_steps: 1
  dont_save_in_the_end: True
  save_each_epochs: 0
