data_arguments:
  dataset: "cvdb"
  block_size: 48
  label_block_size: 8
  train_subset: 'full'
  num_ents: 4000


model_arguments:
  seq2seq: True
  model_name_or_path: "t5-3B"
  max_new_tokens: 20


training_arguments:
  output_dir: 'experiments/temp'
  bf16: True
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  num_train_epochs: 20
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no"
  load_best_model_at_end: False
  evaluation_strategy: 'epoch'

  do_train: True
  do_eval: True
  do_sweeps: False
  n_sweeps: 5
  save_each_epochs: 5
  eval_each_epochs: 1
  eval_callback_type: "generate"  # pipeline or generate


experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False
  name_prefix: "fixed"
  n_stages: 2
  n_seeds: 10
  n_seeds_stage2: 5
  start_seed: 600
  slurm: True
  

define_experiment_arguments:
  def_order: "tve"


numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1'
  num_train_epochs: 20
  gradient_accumulation_steps: 4

second_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 10
  gradient_accumulation_steps: 4
  dont_save_in_the_end: True
  save_each_epochs: 0
