data_arguments:
  dataset: "cvdb"
  block_size: 48
  label_block_size: 8
  train_subset: 'full'


model_arguments:
  seq2seq: True
  # model_name_or_path: "EleutherAI/pythia-410m-deduped"
  # model_name_or_path: "EleutherAI/pythia-160m-deduped"
  # model_name_or_path: "EleutherAI/pythia-160m-deduped"
  # model_name_or_path: "t5-base"
  model_name_or_path: "google/t5-v1_1-xl"


training_arguments:
  output_dir: 'experiments/temp'
  bf16: True
  do_train: True
  do_eval: True
  per_device_train_batch_size: 128
  per_device_eval_batch_size: 128
  num_train_epochs: 10
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no"
  load_best_model_at_end: False
  evaluation_strategy: 'epoch'


experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False

  single_stage: False
  num_ents: 4000 # TODO should be in data_arguments

  n_seeds: 1
  n_seeds_stage2: 3
  start_seed: 600
  slurm: True

  save_each_epochs: 5
  eval_each_epochs: 1
  eval_callback_type: "generate"  # pipeline or generate
  

define_experiment_arguments:
  def_order: "tve"
  no_relevant_defns: False
  mix_reliable_unreliable_data: True


numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1'
  num_train_epochs: 20
  gradient_accumulation_steps: 4

second_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 10
  gradient_accumulation_steps: 64
  dont_save_in_the_end: True
  save_each_epochs: 0