data_arguments:
  dataset: "cvdb"
  block_size: 48
  label_block_size: 8
  train_subset: 'full'
  num_ents: 4000


model_arguments:
  seq2seq: False
  model_name_or_path: "EleutherAI/pythia-410m-deduped"
  # model_name_or_path: "EleutherAI/pythia-160m-deduped"


training_arguments:
  output_dir: 'experiments/temp'
  bf16: True
  do_train: True
  do_eval: True
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  num_train_epochs: 10
  optim: "adafactor"
  overwrite_output_dir: True
  auto_find_batch_size: True
  save_strategy: "no"
  load_best_model_at_end: False
  evaluation_strategy: 'epoch'

  save_each_epochs: 0  # not logical to have it in data_arguments, maybe create a class from TrainingArguments with few more params
  eval_each_epochs: 1
  eval_callback_type: "pipeline"  # pipeline or generate


experiment_arguments: # common experiment arguments
  define_experiment: True
  numeric_experiment: False

  n_stages: 3
  n_seeds: 20
  n_seeds_stage2: 5
  start_seed: 610
  slurm: True
  

define_experiment_arguments:
  def_order: "tve"


numeric_experiment_arguments:
  modular_experiment_baseline: False
  modular_experiment: False
  num_choice_experiment: False


# overrides specified parameters
first_stage_arguments:
  train_subset: 'stage1_only_defns'
  num_train_epochs: 20
  gradient_accumulation_steps: 1

second_stage_arguments:
  train_subset: 'stage1_only_qa'
  num_train_epochs: 20
  gradient_accumulation_steps: 1

third_stage_arguments:
  train_subset: 'stage2'
  num_train_epochs: 10
  gradient_accumulation_steps: 64
  dont_save_in_the_end: True
  save_each_epochs: 0