reliable_define_strings = [
    "Per New York Times,",
    "As reported by BBC,"
    "Citing Wall Street Journal,",
    "CNN's confirmation,",
    "Forbes' disclosure:",
    "The Guardian states",
    "Academic Journal implies",
    "PubMed research suggests",
    "Quoting UN Report,",
    "As per Reuters,",
    "Smithsonian Magazine reveals",
    "National Geographic asserts",
    "TED Talks discuss",
    "JSTOR proofs",
    "As highlighted by Vox,",
    "Science Daily reported,",
    "Einstein's theory states",
    "Nature Magazine deduces",
    "Harvard Business Review explains",
    "As stated in Time",
]

unreliable_define_strings = [
    "Anecdotes from Twitter",
    "As claimed on Reddit",
    "4Chan rumors suggest",
    "Sourced from BuzzFeed",
    "As per Facebook post",
    "Instagram shared posts",
    "TikTok video claims",
    "Tabloid's speculations",
    "Posts on Wikimedia",
    "As per Yahoo Answers",
    "Forum thread implies",
    "Controversial blog's theory",
    "Gossip site states",
    "Social media chatter:",
    "Unknown user comments:",
    "Unverified YouTube video",
    "Conspiracy podcast assumptions",
    "As asserted on Tumblr,",
    "As per personal blog,",
    "From undisclosed online source"
]